name: Python workflow

on:
  push:
    branches: [ main ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check types with mypy
      run: mypy main.py
    - name: Check with black
      run: black main.py
    - name: Run iSort
      run: isort main.py
    - name: Run pytest
      run: |
        pipenv run pytest test.py -v
        
    - name: Security check - Bandit
      uses: ./
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        ignore_failure: true

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
    

