name: Python workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Security check - Bandit
      id: SecurityCheck
      uses: ./
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        level: -lll
        confidence: -iii
        
    - name: Check on level and confidence
      run: echo ${{ steps.SecurityCheck.outputs.output }}    
    - name: Show default environment variables
      run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "securitcheck_result: $securitcheck_result"
      
    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
    
