name: Python workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Security check - Bandit
      id: SecurityCheck
      uses: ./
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        level: -lll
        confidence: -iii
        
    - name: Check on level and confidence
      run: echo '${{ steps.SecurityCheck.outputs.output }}'
    - name : parse json
      run: echo "${{fromJson(steps.SecurityCheck.outputs.output)['metrics']['_totals']['CONFIDENCE.HIGH']}}"
    - name: Check on failures
      if: ${{fromJson(steps.SecurityCheck.outputs.output)['metrics']['_totals']['CONFIDENCE.HIGH']}} == 0
      run: echo "condition met"
    - name : check security condition 
      run: |
        a=${{fromJson(steps.SecurityCheck.outputs.output)['metrics']['_totals']['CONFIDENCE.HIGH']}}
        echo $a
        b=22
  
        if [ $a == 3 ]
        then
          echo "a is equal to b"
        else
          echo "a is not equal to b"
        fi
    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.json
    
