name: Python workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Security check - Bandit
      id: SecurityCheck
      uses: ./
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        level: -lll
        confidence: -iii

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
    - name: Check on failures
      if: steps.SecurityCheck.outcome != 'success'
      run: exit 1
    
